### ISSUE TITLE
nexus 설치

### ISSUE THREAD

**Issue by hellices** [hellices/dev-portal#11]
레포지토리 디펜던시 확인 및 내부환경 셋팅에 활용하기 위해서 별도의 저장소가 필요함.   
aws 샌드박스 eks에 배포   
배포용 헬름 레포 - https://artifacthub.io/packages/helm/sonatype/nexus-repository-manager   

```
The default login is randomized and can be found in /nexus-data/admin.password 
or
 you can get the initial static passwords () by setting the environment variable 
NEXUS_SECURITY_RANDOMPASSWORD to false in your values.yaml
```

NEXUS_SECURITY_RANDOMPASSWORD = false 로 셋팅

퍼블릭 접근 도메인 : http://swa-nexus.shrnd.link/

**Comment by hellices** [comment]
@YOOMYE89 참고하세요

**Comment by YOOMYE89** [comment]
확인 정상 잘 됩니다
