### ISSUE TITLE
샌드박스 서버 개인별 부여

### ISSUE THREAD

**Issue by wijihoon** [hellices/dev-portal#20]
[제안] sandbox (개발자 놀이터)

[내용] backstage에서 GitOps 기반에 설정과 개인 설정 값을 통해 AP서버 부여
ex) jihoon.sandbox.com

[스택] git, gitlab, argoCD, Docker, Ingress 등

[참조]
wiki.aws.shinhancard.internal/wiki/xwktech/view/개발/프로젝트/미니프로젝트/9.배포

**Comment by hellices** [comment]
AWS sandbox와 혼선이 있음   
사내에 구성된 sandbox의 용도와 활용계획이 본부 내 전파될 필요
