### ISSUE TITLE
요구사항 및 목표 수립

### ISSUE THREAD

**Issue by hellices** [hellices/dev-portal#6]
backstage를 통해 만들고 싶은 기능을 나열해보자

**Comment by hellices** [comment]
이렇게 달아보죠
[제안] api docs 기능 추가

[내용] backstage에 등록된 서비스의 api를 관리할 수 있는 기능을 제공한다.
api endpoint와 prameter를 관리하도록 함

- api 등록을 강제화할 수 있는 방안이 있을까? 없으면 관리가 안될듯?
- api 등록 자동화할 수 있는 방법은? 

ref).https://github.com/backstage/backstage/blob/master/plugins/api-docs/README.md

**Comment by hellices** [comment]
[제안] project initializer

[내용] backstage에서 컴포넌트 생성할 때 각각의 프레임워크에 맞는 initial project(repository) 생성

- gitlab repository template 활용
- (java/spring인 경우)genesis core 연동
- (javascript의 경우)next.js, vuejs 등 프로젝트 템플릿 제공

기능개발이 아니고 셋팅으로 해결될지도???

**Comment by jobum97** [comment]
[제안] 방화벽 & DB 권한, 계정 신청

[내용] backstage에서 프로젝트 생성시 해당 프로젝트에 맞는 기본적인 방화벽과 DB 권한 계정 신청 기능

- 각 업무에 필요한 내용들을 프리셋으로 저장하고 이러한 프리셋들을 공유하고 커스텀하여 가져다 쓸 수 있으면 좋을 것 같음

**Comment by hellices** [comment]
tanzu application platform의 [포트폴리오](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/index.html)를 참고해보자.   
why ? [TAP](https://www.youtube.com/watch?v=GAzKCQO8Vt0)가 backstage 기반으로 만들어짐
|기능|doc|검토|요건 추가 여부|
|----|----|---|-------------|
|Speed up application development by providing ready-made, enterprise-conformant code and configurations.|[Application Accelerator for VMware Tanzu Docs](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/application-accelerator-about-application-accelerator.html)|신규 프로젝트를 git repo에서 가져오는 방법으로 backstage component 기능으로 확인|X|
|Get insights into running applications and troubleshoot issues.|[Application Live View for VMware Tanzu Docs](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/app-live-view-about-app-live-view.html)|라이브 컨테이너 디버깅은 보안 이슈가 있을듯<br/> 만약 backstage에서 승인을 받아서 개발 컨테이너를 디버깅할 수 있도록한다면?<br/> hiware 정책과 협의해볼까?|?|
|Install the open-source Carvel tools on your clusters to allow easy installation and management of Tanzu Application Platform and other Tanzu products.|[Cluster Essentials for VMware Tanzu Docs](https://docs.vmware.com/en/Cluster-Essentials-for-VMware-Tanzu/index.html)|[carvel](https://carvel.dev)라는 오픈소스 기반으로 배포 자동화하는 컨셉으로 이해됨<br/> 우리는 gitlab ci / argocd가 표준|X|
|Build serverless and event-driven cloud native applications with enterprise-supported Knative.|[Cloud Native Runtimes for VMware Tanzu Docs](https://docs.vmware.com/en/Cloud-Native-Runtimes-for-VMware-Tanzu/index.html)| knative 기반의 serverless plaform. 미래에 준비해볼지도....|X|
|Support the discoverability, lifecycle management, and connectivity of Service Resources such as databases, message queues, and DNS records.|[Services Toolkit for VMware Tanzu Application Platform Docs](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/services-toolkit-about.html)|Platform 위에서 다른 서비스와 연계(?)하는 기능으로 이해가 됨. 예를 들면 AWS RDS를 배포한다던지.... 논외일듯|X|
|Deploy streaming and batch data pipelines to Kubernetes.|[VMware Spring Cloud Data Flow for Kubernetes Docs](https://docs.vmware.com/en/Spring-Cloud-Gateway-for-VMware-Tanzu/index.html)|링크는 잘못된듯. spring cloud data flow와 통합된 뷰를 제공하는거일듯. 잡마인드가 빠지지 않는한 불필요.|X|
|Route internal or external API requests to application services that expose APIs.|[VMware Spring Cloud Gateway for Kubernetes Docs](https://docs.vmware.com/en/VMware-Spring-Cloud-Gateway-for-Kubernetes/index.html)|Spring Cloud Gateway for Kubernetes handles cross-cutting concerns on behalf of API development teams, such as: Single Sign-On (SSO), access control, rate limiting, resiliency, security, and more. <br/> 배포할 수 있도록 준비하면 좋을듯. 별도의 ingress controller를 배포하지 않고 kubernetes gateway 패턴으로 통합.... 그러나 이번 과제는 아닐지도|?|
|Turn application source code into container images.|[VMware Tanzu Build Service Docs](https://docs.vmware.com/en/VMware-Tanzu-Build-Service/index.html)| gitlab ci와 통합 -논의해보자|?|
|Provide framework and runtime support for applications in different languages to Tanzu Build Service.|[VMware Tanzu Buildpacks Docs](https://docs.vmware.com/en/VMware-Tanzu-Buildpacks/index.html)|buildpacks를 쓰면 jar 배포 후 빌드 자동화가 이루어진다. gitlab ci와 통합하는 과정이 필요한데. 우리 스콥은 아니지만 필요성은 논의해볼 수 있을듯.|X|

**Comment by jobum97** [comment]
[제안] 타 시스템들과의 연결

[내용] 시스템 상세보기 페이지에서 
Definition - swagger
ToDo -jira (도입한다면) 혹은 gitlab 이슈 등 협업툴 연결
연계로 개발자 포털내에서도 내용 확인 가능하고 클릭하면 넘어갈 수 있으면 좋을 것 같음

**Comment by hellices** [comment]
[제안] localstack을 활용한 개발 환경 최적화

[내용] localstack - 로컬에서 cloud native api를 사용할 수 있도록 로컬환경을 구성해주는 솔루션
https://docs.localstack.cloud/
개발환경 initialize 시 같이 배포되도록 하여서 AWS 등의 cloud native api를 사용해야 하는 요건을 aws와 연동하지 않고도 로컬개발을 가능하게 하도록 함

**Comment by hellices** [comment]
[제안] swagger와 통합하여 api generate 자동화

[내용] 1번 제안의 확장으로 api 목록을 직접 작성하는 것이 아니라 배포된 테스트/운영 서비스의 api를 swagger 또는 spring actuator와 연동하여 목록을 제너레이션 해줌.
api의 documentation(swagger annotation)과 통합되면 사용 가이드가 자동으로 만들어질 것으로 기대함

**Comment by hellices** [comment]
[제안] 서비스 구축을 위항 업무 단계를 알려주는 template 제공

[내용] 
컴포넌트 생성 시 배포 타깃 서버, db정보 등을 선택하여 진행
예를 들어 openshift에 배포하기 위해서 필요한 신청서
- itsm openshift 프로젝트 생성 요청
- itsm openshift namespace 생성 요청
- DB 계정 생성 요청

ITSM 요청서와 API 연동 가능할까?
가능하면 API 방식으로
불가능하다면 담당자가 체크해서 확인할 수 있도록
-

**Comment by hellices** [comment]
[제안] 코드 정적분석 결과 확인

[내용] 코드 정적분석 도구와 통합하여 프로젝트의 master/develop 브랜치에 대한 품질지수를 확인할 수 있게 함

**Comment by hellices** [comment]
[제안] 컴포넌트 빌드 및 배포 결과 확인

[내용] gitlab ci / argocd 등의 툴과 연계하여 빌드/배포 결과를 확인할 수 있게 함

**Comment by hellices** [comment]
[제안] 프로젝트 문서화 템플릿 제공

[내용] techdoc plugin과 연동하여 프로젝트의 산출물을 문서화할 수 있도록 템플릿을 제공함

- 프로젝트의 개요
- 개발 셋팅 방법
- 방화벽 오픈 목록
- ERD
- 설계서
- 아키텍처 문서 등

**Comment by jobum97** [comment]
[제안] 유닛/통합 테스트 기능 제공 및 결과 확인

[내용] 각 프로젝트 별로 작성된 유닛/통합 테스트를 (입력값을 넣어) 실행할 수 있고 이에 대한 결과 확인할 수 있는 기능 제공

**Comment by wijihoon** [comment]
[제안] IDE별 유용한 Plugins 제공

[내용] 각 필요에 따라 조립하여 사용할 수 있도록 지원

**Comment by seowjin1060** [comment]
[제안] VM 플랫폼 대상 리소스 정의 기능
[내용]
Backstage는 k8s 기반의 클러스터 환경에서 대부분의 리소스 타입를 지원하지만, (pod, Node, Service등)
Vmware Vsphere, AWS EC2 등의 VM 기반 플랫폼에 대한 정의는 지원하지 않음.
 
Component / Resource로 vmware & AWS 에서 제공하는 VM / image / LB등의 API를 지원하여
SW catalog에서 Vm기반의 구성도를 명시 / 배포할 수 있게 지원
 
[스택]
 - gitlab CI
 - 다른 component와 시스템에 정의된 사항을 vm 기반 리소스에 반영하기 위한 ansible core, chef등의 자동화 도구들
 - Vmware / AWS API를 연동할 Node js 백엔드
 
[예상 이슈]
VM 환경에 대한 제어 권한의 보안성 (pull 방식으로 해결)
 
[참조] backstage issue 3074번
https://github.com/backstage/backstage/issues/3074

**Comment by jobum97** [comment]
[제안] 시스템, 통신의 흐름 시각화

[내용] 해당 프로젝트의 서비스가 어떤 흐름으로 어느 시스템과 통신하고 어떻게 흘러가는지 시각화하여 보여준다.
추가적으로 CIL 혹은 로그 시스템과 연계하면 좋을 듯

[예상 이슈]
정보 보호 관련 이슈가 우려된다

**Comment by seowjin1060** [comment]
[제안] Chaos engineering 모듈

[내용] 위의 제안들을 포함하여 이상적인 backstage는 SW 카탈로그를 통해 한 서비스의 모든 리소스와 컴포넌트에 대한 정의를 가지고 있을것.
이 정의를 이용하여 서비스를 구성하는  특정 리소스 / 컴포넌트의 중단을 시뮬레이션해서 다른 컴포넌트와 리소스에 대한 영향과 서비스의 상태를  테스트할 수 있을것임

[예상 이슈] 
실제 중단을 일으키지 않고 어떻게 다른 컴포넌트에 장애를 시뮬레이션할지 방안 필요
중단 후 복구 로직의 난해함

**Comment by seowjin1060** [comment]
[제안] chat gpt 과제

[내용] 공유된 지주 CEO 의견 착안
사내 사용중인 xwiki  / 인포누리등에 등록된 문서들과 devstage에 작성된 문서  리소스를 정의하고,
정의된 위키 리소스들을 chat gpt에 학습할 수 있는 데이터로 전송 
이후 chat gpt plugin을 통해

**Comment by hellices** [comment]
담당 | 주제 | O - 이슈등록 - - 보류 | 비고
-- | -- | -- | --
황인환 | api docs 기능 추가 | O |  
황인환 | project initializer | O |  
조범수 | 방화벽 & DB 권한, 계정 신청 -> 문서화 + todo list | O |  
` | 라이브 컨테이너 디버깅 | - |  
` | gitlab ci와 통합 | - |  
  | 타 시스템들과의 연결 | - |  
위지훈 | sandbox (개발자 놀이터) | O |  
황인환 | localstack을 활용한 개발 환경 최적화 | O |  
황인환 | swagger와 통합하여 api generate 자동화 | O |  
황인환 | 서비스 구축을 위항 업무 단계를 알려주는 template 제공 | O |  
황인환 | 코드 정적분석 결과 확인 | O |  
황인환 | 컴포넌트 빌드 및 배포 결과 확인 | O |  
황인환 | 프로젝트 문서화 템플릿 제공 | O |  
  | 유닛/통합 테스트 기능 제공 및 결과 확인 | - |  
위지훈 | IDE별 유용한 Plugins 제공 | O |  
서원진 | VM 관련 리소스 지원 범위 확장 | O | 이슈 상세화 및 쪼개기
조범수 | 시스템, 통신의 흐름 시각화 | O |  
  | Chaos engineering 모듈 | - |  
서원진 | chat gpt 사용 페이지 | O |

**Comment by hellices** [comment]
@seowjin1060 @jobum97 @wijihoon 자기가 발의한 거 이슈 등록!
