### ISSUE TITLE
이슈 템플릿 작성

### ISSUE THREAD

**Issue by hellices** [hellices/dev-portal#8]
이슈 작성을 위한 초기 템플릿 구성
이슈 = feature

**Comment by seowjin1060** [comment]
아래 주제들로 분류하려 합니다 
헌데... 프로젝트가 조직 소유가 아니라 직접 템플릿 변경이 불가합니다 ㅠㅠ...
fork된 레포에서 생성된 이슈 템플릿을 가져올수 있는지 보겠습니다 

Bug
Feature 
Improvement
Document
Help
Security
Deployment

**Comment by seowjin1060** [comment]
fork된 레포지토리에서 생성 후 병합 가능한것으로 확인되어 진행하겠습니다
