### ISSUE TITLE
ground rule 수립

### ISSUE THREAD

**Issue by hellices** [hellices/dev-portal#9]
Ground rule 수립, wiki에 작성
ex.)
1주일에 이슈 1개 이상 반드시 처리한다.
PR(pull requests == merge request) 시 모두의 리뷰 코멘트를 받아야 한다.
오프라인 모임을 자제하며 질문 등 모든 논의사항은 깃허브를 통해 수행한다.
주 1회 회고를 진행하며 회고는 오프라인으로 진행한다.
회고는 1시간 이내로 한다.

**Comment by jobum97** [comment]
회고때

**Comment by hellices** [comment]
wiki에 [code of conduct](https://github.com/hellices/dev-portal/wiki/Code-of-Conduct) 작성 완료
7.5(수) 내부 토론 후 확정하였음.
